name=KT_BQ25601
version=1.0.2
author=Kacper Tora
maintainer=Kacper Tora
sentence=Arduino library for Texas Instruments BQ25601 I2C battery charger.
paragraph=Supports full charge control, input current limits, safety timers, thermal regulation and status monitoring.
category=Device Control
url=https://github.com/KacperTora/KT_BQ25601
architectures=*
includes=KT_BQ25601.h